### ISSUE TITLE
 BeagleBone => Port Expander + ESP

### ISSUE THREAD

**Issue by dominikjeske** [maciejkrasuski/boneIO#2]
W tym momencie do obsługi IO wykorzystywany jest BeagleBone który podbija cenę urządzenia które dodatkowo się trochę marnuje ponieważ głównym jego zadaniem jest wysterowanie przekaźników i odczyt wejść. Bardziej ekonomicznym rozwiązaniem było by zastosowanie:

1. Port Expandera - w urządzeniach które mam teraz ([HSRel8](http://www.cctools.eu/ext_index.php/artikel/1818) i [I2C-Port 16 HS](http://www.cctools.eu/ext_index.php/artikel/1818)) jest zastosowany MAX7311 ale może jest coś lepszego
2. ESP32 - do połączenia z expanderem i wysyłaniu sygnałów MQQT z input oraz odbieraniem ich do wysterowania przekaźnikami

**Comment by maciejkrasuski** [comment]
Moduł esp jest już realizowany jako kolejny element projektu.
