### ISSUE TITLE
Wykorzystanie wyjść NC

### ISSUE THREAD

**Issue by Pawellbn** [maciejkrasuski/boneIO#28]
Proponuję bardzo małą zmianę w projekcie, aby dać możliwość wykorzystania 2 lub 4 styków NC.
Połączyć K9-Pad12 lub 22 poprzez zworę (pod przekaźnikiem K10) z J6-Pad3 oraz K8-Pad12 lub 22 poprzez zworę (pod przekaźnikiem K10) z J6-Pad4. Analogicznie po drugiej stronie z K18, K19 i K20.

W ten sposób rezygnując z przekaźnika K10 dostaniemy wyjścia NC z przekaźników K8 i K9. Dodatkowo rezygnując z  przekaźnika K20 dostaniemy wyjścia NC z przekaźników K18 i K19.

**Comment by maciejkrasuski** [comment]
Do rolet zrobimy inną płytkę dolną - temat zaadresowany i ma to ogarnąć Radek. Zamykam issue.
