### ISSUE TITLE
Górna PCB z BBB schemat

### ISSUE THREAD

**Issue by kamil2466** [maciejkrasuski/boneIO#35]
Dodaje schemat górnej płytki, zobaczcie czy jest ok czy nie, co dodać co usunąć, jakieś wasze opinie mile widziane i sugestie. Jutro PCB z widoku 3D powinno się udać wykonać.
![bbb](https://user-images.githubusercontent.com/37997460/138493206-824cd566-e572-43aa-af23-9649a8ccfaf4.jpg)
![clock](https://user-images.githubusercontent.com/37997460/138493475-07133d86-f527-47d0-85aa-f18b07f807c7.jpg)
![i2c](https://user-images.githubusercontent.com/37997460/138493605-feaeeb53-76d7-43f8-bd5d-7c2528958edf.jpg)
![izolacja24v](https://user-images.githubusercontent.com/37997460/138493634-1739bdf0-7733-4b44-9bc3-b9404db0db65.jpg)
![Pin_down](https://user-images.githubusercontent.com/37997460/138493660-9b6eaa7a-6aec-499a-a9f7-72bcf861f981.jpg)
![Pin_out1](https://user-images.githubusercontent.com/37997460/138493672-f9982335-4f3c-46aa-b383-ea0629e43524.jpg)
![Pin_out2](https://user-images.githubusercontent.com/37997460/138493688-ebc649ed-737a-4488-a887-95df8a61be14.jpg)
![pullup](https://user-images.githubusercontent.com/37997460/138493703-58f5b955-8c36-4f88-a01e-ff71b5858399.jpg)
![zasilanie](https://user-images.githubusercontent.com/37997460/138493717-95f83027-4e24-4853-a28f-554645acf456.jpg)

**Comment by maciejkrasuski** [comment]
to już chyba trochę nieaktualne - aktualne schematy w pull requestach - zamykam.
